#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "../..");
const NODE_MODULES = path.join(ROOT, "node_modules");
const PACKAGE_JSON = path.join(ROOT, "package.json");
const NOTICES_PATH = path.join(ROOT, "THIRD_PARTY_NOTICES.md");

const ALLOWED = new Set(["MIT", "ISC", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "0BSD"]);

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function readDependencyLicense(depName) {
  const depPkg = path.join(NODE_MODULES, depName, "package.json");
  if (!fs.existsSync(depPkg)) {
    return { name: depName, version: "(missing)", license: "UNKNOWN", missing: true };
  }

  const pkg = readJson(depPkg);
  let license = pkg.license || "UNKNOWN";
  if (typeof license === "object") license = JSON.stringify(license);
  return {
    name: pkg.name || depName,
    version: pkg.version || "unknown",
    license: String(license),
    repository: typeof pkg.repository === "string" ? pkg.repository : (pkg.repository && pkg.repository.url) || "",
    missing: false,
  };
}

function writeNotices(entries) {
  const lines = [];
  lines.push("# THIRD_PARTY_NOTICES");
  lines.push("");
  lines.push("Generated by `node scripts/validate/license_audit.js`.");
  lines.push("");
  lines.push("| Package | Version | License | Repository |");
  lines.push("|---|---:|---|---|");
  for (const entry of entries) {
    lines.push(`| ${entry.name} | ${entry.version} | ${entry.license} | ${entry.repository || ""} |`);
  }
  lines.push("");
  fs.writeFileSync(NOTICES_PATH, lines.join("\n") + "\n", "utf8");
}

function main() {
  const pkg = readJson(PACKAGE_JSON);
  const deps = Object.assign({}, pkg.dependencies || {}, pkg.devDependencies || {});
  const names = Object.keys(deps).sort();

  const entries = names.map(readDependencyLicense);
  writeNotices(entries);

  const violations = [];
  for (const entry of entries) {
    if (entry.missing) {
      violations.push(`${entry.name}: not installed`);
      continue;
    }
    if (!ALLOWED.has(entry.license)) {
      violations.push(`${entry.name}@${entry.version}: non-allowlisted license ${entry.license}`);
    }
  }

  if (violations.length) {
    console.error("phase7_license_status FAIL");
    for (const v of violations) console.error("  - " + v);
    process.exit(1);
  }

  console.log(`License audit passed for ${entries.length} direct dependencies.`);
  console.log("phase7_license_status PASS");
}

main();
